### ISSUE TITLE
Feature: Add routing UI

### ISSUE THREAD

**Issue by saerdnaer** [wheelapp/wheelapp-frontend#1]
**Is your feature request related to a problem? Please describe.**
As a wheelmap user, I'd like to get detailed navigation information to get from my current position to the target location

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

## TODOS
* [ ] add https://github.com/wheelapp/leaflet-routing-machine to frontend
* [ ] integrate https://openrouteservice.org/dev/#/api-docs/v2/directions/{profile}/get
* [ ] …
* [ ] improve UI and UX
